### ISSUE TITLE
Actions in footer not working

### ISSUE THREAD

**Issue by anze3db** [Textualize/trogon#85] opened 2024-07-05 00:16 UTC
I have noticed that actions in the footer no longer work by clicking them or using keyboard shortcuts (C^t, C^s, etc).

The `BINDINGS` defined in the `CommandBuilder` class no longer propagate to the parent `Trogon` class, where the handlers are defined (e.g., `action_focus_command_tree`). 

Moving the `BINDINGS` to the Trogon class fixes the problem for me. Moving the handlers down to the `CommandBuilder` does as well, but I'm not sure which solution is better. Could this be an underlying issue with Textual? 

I'm happy to open a PR and move the BINDINGS, just let me know if this is an ok solution.

**Comment by daneah** [comment] 2024-08-14 15:26
Is this potentially a duplicate of #82 ?

**Comment by anze3db** [comment] 2024-08-14 20:52
Ah, yes. Looks like a duplicate. Closing this one, thanks!

**Closed** 2024-08-14 20:53 UTC
